### ISSUE TITLE
Support pr comments in addition to annotations

### ISSUE THREAD

**Issue by moritzzimmer** [terraform-linters/setup-tflint#142]
I was wondering if you could add support for commenting pull-requests in addition to annotations (e.g. like in [tfsec-pr-commenter-action](https://github.com/aquasecurity/tfsec-pr-commenter-action#example-pr-comment)).

IMO this could make tflint violations more visible in PR workflows.

**Comment by bendrucker** [comment]
Interesting, but not planned. Annotations come effectively for free via problem matchers.

Turning those into comments would be a whole separate action. And if you review the example, this is a non-trivial feature.
