### ISSUE TITLE
Wrapper that sets stdout, stderr, exit code outputs

### ISSUE THREAD

**Issue by dreinhardt89** [terraform-linters/setup-tflint#171]
It would be great if a wrapper installed to expose stdout, stderr, and exit code so we could easily reference it in another GHA step (i.e. adding a PR comment if exit code = 2).

[setup-terraform](https://github.com/hashicorp/setup-terraform) has one [here](https://github.com/hashicorp/setup-terraform/blob/5aa9444145a940d669e4b92ef8a1821f0f4749da/wrapper/terraform.js#L25) as an example.

**Comment by bendrucker** [comment]
I'm of the opinion that having that on by default for `setup-terraform` was a mistake:

https://github.com/hashicorp/setup-terraform/issues/167#issuecomment-1091202764

Happy to accept a PR that adds one that's disabled by default.

**Comment by dreinhardt-terminus** [comment]
@bendrucker PR for you when you get a chance: https://github.com/terraform-linters/setup-tflint/pull/173

**Comment by dreinhardt-terminus** [comment]
@bendrucker any update? happy to make changes if any are needed.

**Comment by dreinhardt-terminus** [comment]
@bendrucker any update?
