### ISSUE TITLE
feature request - change problem matcher variable to be relative to checkout-dir.

### ISSUE THREAD

**Issue by bnayah** [terraform-linters/setup-tflint#19]
I have a monorepo of terraform modules.

Basic structure is as follows:

git root/
             .github/
             .githuh/worksflows/*.yml
             .github/matchers.json
             aws/accounts/prod/us-east-1/
             aws/modules/vpc
             aws/organizations
             
Each 'account' folder is run by a separate github action, and has a separate state.

The issue is when using problem matchers. 
The [code](https://github.com/terraform-linters/setup-tflint/blob/master/src/setup-tflint.js#L88) assumes that the working directory is at the root of the checkout folder.

Since this is not the case in my flow, the matchers.json is not found.

Action should support variable 'working_directory' to enable module inspection. 
Currently I Change directory to the target directory, however the matchers.json directory needs to be relative to the root of the checkout, not the current directory.

**Comment by bendrucker** [comment]
The matcher file being added is this, you should not be supplying your own:

https://github.com/terraform-linters/setup-tflint/blob/master/.github/matchers.json

`__dirname` is the correct path, relative to the calling script. If you want to discuss further, we need an example of your workflow.
