### ISSUE TITLE
Deprecated errors on action use

### ISSUE THREAD

**Issue by LKay** [terraform-linters/setup-tflint#4]
The example from README results in errors in Action Runner as follow:
```
/usr/bin/unzip -q /home/runner/work/_temp/3f1bd42c-6fbe-4592-a37c-7554c1ca8846
Error: Unable to process command '::add-path::/home/runner/tflint/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
```

This might be related to https://github.com/actions/toolkit/issues/630 . So far the only solution for me was to include envvar like:
```
      - uses: lablabs/setup-tflint@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          tflint_version: v0.24.1
```

**Comment by bendrucker** [comment]
This is a tag issue, using `@1.0.3` should fix that. That should be `v1.0.3` for consistency with the other versions.

Something like https://github.com/marketplace/actions/update-major-minor-semver can work nicely for keeping the major tag that's presented in the readme in sync automatically.

**Comment by bendrucker** [comment]
https://github.com/terraform-linters/setup-tflint/commit/edec398ea4cc569ec14dda571e11ebb72cd92c74 implements automatic tagging, so this is now resolved. The major and minor semver tags will be updated automatically each time a new full semver tag is pushed.
