### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by jug-smile** [terraform-linters/setup-tflint#88]
Hi,
  
  I have the following code:
      
      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
 
 Which results in the following error:  
 
 ............
  Check: CKV_DOCKER_2: "Ensure that HEALTHCHECK instructions have been added to container images"
  	SKIPPED for resource: /resources/containers/simulator/Dockerfile.
  	Suppress comment:  No need for health check
  	File: /resources/containers/simulator/Dockerfile:1-20
  	Guide: https://docs.bridgecrew.io/docs/ensure-that-healthcheck-instructions-have-been-added-to-container-images
 
  
  Wrote output in SARIF format to the file 'results.sarif'
  Error: An error occurred trying to start process '/home/runner/actions-runner/externals/node12/bin/node' with working directory '/home/runner/actions-runner/_work/connected-sports-platform/connected-sports-platform'. Argument list too long
  
  Please, any help will be appreciated.
  
  Thanks.
  
  Regards.

**Comment by bendrucker** [comment]
Are you saying that invoking the action alone is causing this error? It seems highly unlikely that this could be a problem with the action, given the passing tests. The SARIF error would also have nothing to do with the action. We'll need a clear reproduction to proceed.

**Comment by jug-smile** [comment]
Hi @bendrucker,

It seems that I have a lot autogenerated files (java classes and jars) in another folder which results in that error. Is there a way to restrict the terraform-linters/setup-tflint@v1 to a given folder?

Thanks.

**Comment by bendrucker** [comment]
All the action does is install TFLint. The contents of the working directory should have no impact on the action. What you've shared doesn't add up.

**Comment by jug-smile** [comment]
I fixed the issue,

It resulted from a previous step. The action: bridgecrewio/checkov-action@master seems to not support many nesting levels (generated from a springboot project). I have moved the java folder to another location not accessible from this action and only left the Terraform sources. It works fine now.

Thanks for your help @bendrucker.
